services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - CERT_PATH=${CERT_PATH}
      - KEY_PATH=${KEY_PATH}
      - WORDPRESS_FPM_PORT=${WORDPRESS_FPM_PORT:-9000}
      - ADMINER_PORT=${ADMINER_PORT:-9001}
      - PORTAINER_PORT=${PORTAINER_PORT:-9000}
      - STATIC_SITE_PORT=${STATIC_SITE_PORT:-80}
    ports:
      - "${NGINX_HTTPS_PORT:-443}:443"
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/wordpress
    restart: always
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        WORDPRESS_FPM_PORT: ${WORDPRESS_FPM_PORT:-9000}
    container_name: wordpress
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MARIADB_PORT=${MARIADB_PORT:-3306}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - WP_USER_ROLE=${WP_USER_ROLE}
      - WORDPRESS_FPM_PORT=${WORDPRESS_FPM_PORT:-9000}
    secrets:
      - db_password
      - credentials
      - user_credentials
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - mariadb
      - redis
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        MARIADB_PORT: ${MARIADB_PORT:-3306}
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MARIADB_PORT=${MARIADB_PORT:-3306}
    secrets:
      - db_password
      - db_root_password
    networks:
      - inception_network
    volumes:
      - mariadb_data:/var/lib/mysql
  redis:
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
      args:
        REDIS_PORT: ${REDIS_PORT:-6379}
    container_name: redis
    environment:
      - REDIS_PORT=${REDIS_PORT:-6379}
    networks:
      - inception_network
    restart: always
  ftp:
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    container_name: ftp
    volumes:
      - wordpress_data:/var/www/wordpress
    secrets:
      - user_credentials
      - credentials
    ports:
      - "${FTP_PORT:-21}:21"
      - "${FTP_PASSIVE_MIN:-21100}-${FTP_PASSIVE_MAX:-21110}:21100-21110"
    networks:
      - inception_network
    restart: always
  portainer:
    build:
      context: ./requirements/bonus/portainer
      dockerfile: Dockerfile
      args:
        PORTAINER_PORT: ${PORTAINER_PORT:-9000}
    container_name: portainer
    restart: always
    environment:
      - PORTAINER_PORT=${PORTAINER_PORT:-9000}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    secrets:
      - portainer_pass
    networks:
      - inception_network
  static_site:
    build:
      context: ./requirements/bonus/static_site
      dockerfile: Dockerfile
      args:
        STATIC_SITE_PORT: ${STATIC_SITE_PORT:-80}
    container_name: static_site
    restart: always
    environment:
      - STATIC_SITE_PORT=${STATIC_SITE_PORT:-80}
    networks:
      - inception_network
  adminer:
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
      args:
        ADMINER_PORT: ${ADMINER_PORT:-9001}
    container_name: adminer
    restart: always
    environment:
      - ADMINER_PORT=${ADMINER_PORT:-9001}
    networks:
      - inception_network
    depends_on:
      - mariadb

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt
  user_credentials:
    file: ../secrets/user_credentials.txt
  portainer_pass:
    file: ../secrets/portainer_pass.txt

networks:
  inception_network:
    name: inception_network
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/omizin/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/omizin/data/wordpress
  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/omizin/data/portainer
