services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - CERT_PATH=${CERT_PATH}
      - KEY_PATH=${KEY_PATH}
    ports:
      - "443:443"
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/wordpress
    restart: always
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - WP_USER_ROLE=${WP_USER_ROLE}
    secrets:
      - db_password
      - credentials
      - user_credentials
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - mariadb
      - redis
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    secrets:
      - db_password
      - db_root_password
    networks:
      - inception_network
    volumes:
      - mariadb_data:/var/lib/mysql
  redis:
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    container_name: redis
    networks:
      - inception_network
    restart: always
  ftp:
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    container_name: ftp
    volumes:
      - wordpress_data:/var/www/wordpress
    secrets:
      - user_credentials
      - credentials
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    networks:
      - inception_network
    restart: always
  portainer:
    build:
      context: ./requirements/bonus/portainer
      dockerfile: Dockerfile
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    secrets:
      - portainer_pass
    networks:
      - inception_network

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt
  user_credentials:
    file: ../secrets/user_credentials.txt
  portainer_pass:
    file: ../secrets/portainer_pass.txt

networks:
  inception_network:
    name: inception_network
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/omizin/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/omizin/data/wordpress
  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/omizin/data/portainer
